namespace MyShoppingCart.Application.Tests.Validators.Helpers;

public static class LongStrings
{
    public const string LONG_STRING_51 = "xznbqnpwltundqbukbmykggwceuunackjjfoccalylyugrfxqmx";
    public const string LONG_STRING_501 = "xznbqnpwltundqbukbmykggwceuunackjjfoccalylyugrfxqmxznbqnpwltundqbukbmykggwceuunackjjfoccalylyugrfxqmxznbqnpwltundqbukbmykggwceuunackjjfoccalylyugrfxqmxznbqnpwltundqbukbmykggwceuunackjjfoccalylyugrfxqmxznbqnpwltundqbukbmykggwceuunackjjfoccalylyugrfxqmxznbqnpwltundqbukbmykggwceuunackjjfoccalylyugrfxqmxznbqnpwltundqbukbmykggwceuunackjjfoccalylyugrfxqmxznbqnpwltundqbukbmykggwceuunackjjfoccalylyugrfxqmxznbqnpwltundqbukbmykggwceuunackjjfoccalylyugrfxqmxznbqnpwltundqbukbmykggwceuunackjjfoccalylyugrfxqms";
}
