global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Options;
global using static Microsoft.AspNetCore.Http.Results;
global using MyShoppingCart.Api.Utilities;
global using MyShoppingCart.Domain.Setup;
global using MyShoppingCart.Domain.Mediator;
global using MyShoppingCart.Application.Customers;
global using MyShoppingCart.Application.Orders;
global using MyShoppingCart.Application.Products;
